"""Add new column

Revision ID: b5cad2a3aca6
Revises: 
Create Date: 2024-02-28 12:17:54.450656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5cad2a3aca6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'point_of_reference')
    op.add_column('users', sa.Column('point_of_reference', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'point_of_reference')
    op.add_column('messages', sa.Column('point_of_reference', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
