"""delete column

Revision ID: e4ebefb40c47
Revises: 0f03d82d6a97
Create Date: 2024-02-29 09:12:00.680928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ebefb40c47'
down_revision: Union[str, None] = '0f03d82d6a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'cancellation_trigger')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('cancellation_trigger', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
